### ISSUE TITLE
Alignments: create new type of mapping to help with curations?

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#272]
I am looking at the slurp file : https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/slurp/doid.tsv

Many of the terms in this list (suggested to be new terms in Mondo) already exist in Mondo. For example: 

mondo_id | mondo_label | xref | xref_source | original_label | definition | parents
-- | -- | -- | -- | -- | -- | --
MONDO:0850393 | intracranial berry aneurysm 1 | DOID:0080964 | MONDO:equivalentTo | intracranial berry aneurysm 1 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 7q11.2. | MONDO:0016483\|MONDO:0000426
MONDO:0850394 | intracranial berry aneurysm 2 | DOID:0080965 | MONDO:equivalentTo | intracranial berry aneurysm 2 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 19q13. | MONDO:0016483
MONDO:0850395 | intracranial berry aneurysm 3 | DOID:0080966 | MONDO:equivalentTo | intracranial berry aneurysm 3 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 1p36. | MONDO:0016483\|MONDO:0000426
MONDO:0850396 | intracranial berry aneurysm 4 | DOID:0080967 | MONDO:equivalentTo | intracranial berry aneurysm 4 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 5p15.2-p14.3. | MONDO:0016483
MONDO:0850397 | intracranial berry aneurysm 5 | DOID:0080968 | MONDO:equivalentTo | intracranial berry aneurysm 5 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome Xp22. | MONDO:0016483
MONDO:0850398 | intracranial berry aneurysm 6 | DOID:0080969 | MONDO:equivalentTo | intracranial berry aneurysm 6 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 9p21. | MONDO:0016483
MONDO:0850399 | intracranial berry aneurysm 7 | DOID:0080970 | MONDO:equivalentTo | intracranial berry aneurysm 7 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 11q24-q25. | MONDO:0016483
MONDO:0850400 | intracranial berry aneurysm 8 | DOID:0080971 | MONDO:equivalentTo | intracranial berry aneurysm 8 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 14q23. | MONDO:0016483
MONDO:0850401 | intracranial berry aneurysm 9 | DOID:0080972 | MONDO:equivalentTo | intracranial berry aneurysm 9 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 2q33.1. | MONDO:0016483
MONDO:0850402 | intracranial berry aneurysm 10 | DOID:0080973 | MONDO:equivalentTo | intracranial berry aneurysm 10 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 8q12.1. | MONDO:0016483
MONDO:0850403 | intracranial berry aneurysm 11 | DOID:0080974 | MONDO:equivalentTo | intracranial berry aneurysm 11 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and has been mapped to chromosome 8p22. | MONDO:0016483
MONDO:0850404 | intracranial berry aneurysm 12 | DOID:0080975 | MONDO:equivalentTo | intracranial berry aneurysm 12 | An intracranial berry aneurysm that is characterized by rupture of an intracranial aneurysm, an outpouching or sac-like widening of a cerebral artery, leads to a subarachnoid hemorrhage, a sudden-onset disease that can lead to severe disability and death and that has_material_basis_in heterozygous mutation in the THSD1 gene on chromosome 13q14. | MONDO:0016483

These are probably the same as:
![Screenshot 2023-04-10 at 10 32 47 AM](https://user-images.githubusercontent.com/12737987/230957815-b15ae7ae-c013-4b34-ac33-21cb6f14708d.png)

Could we set up additional mapping rules or reports that could help or support curation? (so I don't have to manually check every 12 types of intracranial berry aneurysm to ensure they are the same in DO and Mondo; and the same with other terms)

Some ideas would be: 
- mapping on OMIM x-ref (only omim x-ref). 
- lex matching when the words are "mix up". 
?

Note: if this work would take longer than me doing it manually, I can do it manually. But it might help us in the long term.

**Comment by sabrinatoro** [comment]
another example: 

mondo_id | mondo_label | xref | xref_source | original_label
-- | -- | -- | -- | --
MONDO:0850061 | nipah virus encephalitis | DOID:0050192 | MONDO:equivalentTo | Nipah virus encephalitis

This term is probably the same as 
'Nipah virus disease' (MONDO:0020499)

For this one, the exact synonym is: 'Nipah encephalitis'
We decided to only match if all the words were in the label/synonym. However, if we could have a simple report with these "not exactly exact match for the potential new terms in the slurp file" that we can review, it would help

**Comment by matentzn** [comment]
@hrshdhgd Example to start with:


```
http://purl.obolibrary.org/obo/MONDO_0007111         <skos:exactMatch rdf:resource="https://omim.org/entry/105800"/>
http://purl.obolibrary.org/obo/DOID_0080964         <skos:exactMatch rdf:resource="https://omim.org/entry/105800"/>
```

Why is the lexmatch pipeline not finding that MONDO_0007111 -exactMatch-> DOID_0080964?

**Comment by hrshdhgd** [comment]
```
DOID:0080964	intracranial berry aneurysm 1	skos:closeMatch	MONDO:0007111	aneurysm, intracranial berry type 1	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:105800		
```

This is because `lexmatch` tags it as a `skos:closeMatch` in the `mondo-sources-all-lexical.sssom.tsv` file (not version controlled since it is too large).

**Comment by hrshdhgd** [comment]
Full mention
```
subject_id	subject_label	predicate_id	object_id	object_label	mapping_justification	mapping_tool	confidence	subject_match_field	object_match_field	match_string	subject_preprocessing	object_preprocessing
DOID:0080964	intracranial berry aneurysm 1	skos:closeMatch	MONDO:0007111	aneurysm, intracranial berry type 1	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:105800		
DOID:0080964	intracranial berry aneurysm 1	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:105800		
DOID:0080965	intracranial berry aneurysm 2	skos:closeMatch	MONDO:0012053	aneurysm, intracranial berry, 2	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:608542		
DOID:0080965	intracranial berry aneurysm 2	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:608542		
DOID:0080966	intracranial berry aneurysm 3	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:609122		
DOID:0080966	intracranial berry aneurysm 3	skos:closeMatch	MONDO:0012194	aneurysm, intracranial berry, 3	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:609122		
DOID:0080967	intracranial berry aneurysm 4	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:610213		
DOID:0080967	intracranial berry aneurysm 4	skos:closeMatch	MONDO:0012443	aneurysm, intracranial berry, 4	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:610213		
DOID:0080968	intracranial berry aneurysm 5	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:300870		
DOID:0080968	intracranial berry aneurysm 5	skos:closeMatch	MONDO:0010468	aneurysm, intracranial berry, 5	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:300870		
DOID:0080969	intracranial berry aneurysm 6	skos:closeMatch	MONDO:0012752	aneurysm, intracranial berry, 6	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:611892		
DOID:0080969	intracranial berry aneurysm 6	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:611892		
DOID:0080970	intracranial berry aneurysm 7	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612161		
DOID:0080970	intracranial berry aneurysm 7	skos:closeMatch	MONDO:0012810	aneurysm, intracranial berry, 7	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612161		
DOID:0080971	intracranial berry aneurysm 8	skos:closeMatch	MONDO:0012811	aneurysm, intracranial berry, 8	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612162		
DOID:0080971	intracranial berry aneurysm 8	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612162		
DOID:0080972	intracranial berry aneurysm 9	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612586		
DOID:0080972	intracranial berry aneurysm 9	skos:closeMatch	MONDO:0012949	aneurysm, intracranial berry, 9	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612586		
DOID:0080973	intracranial berry aneurysm 10	skos:closeMatch	MONDO:0012950	aneurysm, intracranial berry, 10	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612587		
DOID:0080973	intracranial berry aneurysm 10	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:612587		
DOID:0080974	intracranial berry aneurysm 11	skos:closeMatch	MONDO:0013654	aneurysm, intracranial berry, 11	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:614252		
DOID:0080974	intracranial berry aneurysm 11	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:614252		
DOID:0080975	intracranial berry aneurysm 12	skos:closeMatch	Orphanet:231160	Familial cerebral saccular aneurysm	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:618734		
DOID:0080975	intracranial berry aneurysm 12	skos:closeMatch	MONDO:0032891	aneurysm, intracranial berry, 12	semapv:LexicalMatching	oaklib	0.5	oio:hasDbXref	oio:hasDbXref	omim:618734		
```

**Comment by matentzn** [comment]
But the config says "exact": https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/config/mondo-match-rules.yaml#L42

Can you change this so that match on exact match is "exact"?

**Comment by hrshdhgd** [comment]
That's because `- oio:hasDbXref` was commented out based on some discussion in the past. I'll uncomment it and run again to see what happens.

**Comment by matentzn** [comment]
No, they are both skos exaxt match. Don't use hasDbXref! Something is going wrong if not both sources have skos exact match!

**Comment by hrshdhgd** [comment]
Digging deeper... 

These are parts of the `merged.db.lexical.yaml` which is the `lexical_index` of `merged.db`. I did a search for `105800` and these were what I found.
```
omimps:105800:
    term: omimps:105800
    relationships:
    - predicate: oio:hasDbXref
      element: DOID:0060228
      element_term: OMIMPS:105800
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasDbXref
      element: MONDO:0016483
      element_term: OMIMPS:105800
      pipeline:
      - default
      synonymized: false

omim:105800:
    term: omim:105800
    relationships:
    - predicate: oio:hasDbXref
      element: DOID:0080964
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasDbXref
      element: MONDO:0007111
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasDbXref
      element: Orphanet:231160
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false

aneurysm, intracranial berry, 1:
    term: aneurysm, intracranial berry, 1
    relationships:
    - predicate: oio:hasRelatedSynonym
      element: MONDO:0007111
      element_term: aneurysm, intracranial berry, 1
      pipeline:
      - default
      synonymized: false
    - predicate: rdfs:label
      element: OMIM:105800
      element_term: aneurysm, intracranial berry, 1
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasExactSynonym
      element: OMIM:105800
      element_term: aneurysm, intracranial berry, 1
      pipeline:
      - default
      synonymized: false

aneurysmal subarachnoid hemorrhage, familial:
    term: aneurysmal subarachnoid hemorrhage, familial
    relationships:
    - predicate: oio:hasRelatedSynonym
      element: MONDO:0007111
      element_term: aneurysmal subarachnoid hemorrhage, familial
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasExactSynonym
      element: OMIM:105800
      element_term: aneurysmal subarachnoid hemorrhage, familial
      pipeline:
      - default
      synonymized: false

anib1:
    term: anib1
    relationships:
    - predicate: oio:hasExactSynonym
      element: OMIM:105800
      element_term: ANIB1
      pipeline:
      - default
      synonymized: false
``` 

And a quick search of `DOID:0080964` revealed:

```
intracranial berry aneurysm 1:
    term: intracranial berry aneurysm 1
    relationships:
    - predicate: rdfs:label
      element: DOID:0080964
      element_term: intracranial berry aneurysm 1
      pipeline:
      - default
      synonymized: false


  omim:105800:
    term: omim:105800
    relationships:
    - predicate: oio:hasDbXref
      element: DOID:0080964
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasDbXref
      element: MONDO:0007111
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasDbXref
      element: Orphanet:231160
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false
```

Am I missing something? I do not see an `exactMatch` predicate for the rules to kick in.

**Comment by matentzn** [comment]
Well they should be there! The exact matches.. check the raw owl files going in before db state and see if they are in there.

**Comment by hrshdhgd** [comment]
merged.owl

```
<!-- http://purl.obolibrary.org/obo/MONDO_0007111 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0007111">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0016483"/>
        <oboInOwl:hasDbXref>MESH:C566284</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>OMIM:105800</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>UMLS:C1862932</oboInOwl:hasDbXref>
        <oboInOwl:hasRelatedSynonym>aneurysm, intracranial berry, 1</oboInOwl:hasRelatedSynonym>
        <oboInOwl:hasRelatedSynonym>aneurysmal subarachnoid hemorrhage, familial</oboInOwl:hasRelatedSynonym>
        <oboInOwl:id>MONDO:0007111</oboInOwl:id>
        <rdfs:label>aneurysm, intracranial berry type 1</rdfs:label>
        <skos:exactMatch rdf:resource="http://identifiers.org/mesh/C566284"/>
        <skos:exactMatch rdf:resource="http://linkedlifedata.com/resource/umls/id/C1862932"/>
        <skos:exactMatch rdf:resource="https://omim.org/entry/105800"/>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#subClassOf"/>
        <owl:annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0016483"/>
        <oboInOwl:source>DC-OMIM:105800</oboInOwl:source>
        <oboInOwl:source>OMIM:105800</oboInOwl:source>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        <owl:annotatedTarget>MESH:C566284</owl:annotatedTarget>
        <oboInOwl:source>MONDO:equivalentTo</oboInOwl:source>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        <owl:annotatedTarget>OMIM:105800</owl:annotatedTarget>
        <oboInOwl:source>MONDO:equivalentTo</oboInOwl:source>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        <owl:annotatedTarget>UMLS:C1862932</owl:annotatedTarget>
        <oboInOwl:source>MONDO:equivalentTo</oboInOwl:source>
        <oboInOwl:source>MONDO:ncbi_mim2gene_medline</oboInOwl:source>
        <oboInOwl:source>OMIM:105800</oboInOwl:source>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym"/>
        <owl:annotatedTarget>aneurysm, intracranial berry, 1</owl:annotatedTarget>
        <oboInOwl:hasDbXref>MONDO:Lexical</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>OMIM:105800</oboInOwl:hasDbXref>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym"/>
        <owl:annotatedTarget>aneurysmal subarachnoid hemorrhage, familial</owl:annotatedTarget>
        <oboInOwl:hasDbXref>OMIM:105800</oboInOwl:hasDbXref>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2004/02/skos/core#exactMatch"/>
        <owl:annotatedTarget rdf:resource="http://identifiers.org/mesh/C566284"/>
        <sssom:mapping_justification rdf:resource="https://w3id.org/semapv/UnspecifiedMatching"/>
        <sssom:subject_label>aneurysm, intracranial berry type 1</sssom:subject_label>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2004/02/skos/core#exactMatch"/>
        <owl:annotatedTarget rdf:resource="http://linkedlifedata.com/resource/umls/id/C1862932"/>
        <sssom:mapping_justification rdf:resource="https://w3id.org/semapv/UnspecifiedMatching"/>
        <sssom:subject_label>aneurysm, intracranial berry type 1</sssom:subject_label>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0007111"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2004/02/skos/core#exactMatch"/>
        <owl:annotatedTarget rdf:resource="https://omim.org/entry/105800"/>
        <sssom:mapping_justification rdf:resource="https://w3id.org/semapv/UnspecifiedMatching"/>
        <sssom:object_label>aneurysm, intracranial berry, 1</sssom:object_label>
        <sssom:subject_label>aneurysm, intracranial berry type 1</sssom:subject_label>
    </owl:Axiom>


<!-- http://purl.obolibrary.org/obo/MONDO_0016483 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0016483">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0003847"/>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0005291"/>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0015145"/>
        <obo:IAO_0000115>An intracranial aneurysm with a characteristic rounded shape; the most common form of cerebral aneurysm.</obo:IAO_0000115>
        <mondo:excluded_from_qc_check rdf:resource="http://purl.obolibrary.org/obo/mondo/sparql/qc/general/qc-single-child.sparql"/>
        <mondo:should_conform_to rdf:resource="http://purl.obolibrary.org/obo/mondo/patterns/OMIM_phenotypic_series.yaml"/>
        <oboInOwl:hasDbXref>DOID:0060228</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>HP:0007029</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>OMIMPS:105800</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>Orphanet:231160</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>SCTID:703226008</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>UMLS:CN230268</oboInOwl:hasDbXref>
        <oboInOwl:hasExactSynonym>aneurysm, intracranial berry</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>familial aneurysmal subarachnoid hemorrhage</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>familial berry aneurysm</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>familial intracranial saccular aneurysm</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>saccular cerebral aneurysm</oboInOwl:hasExactSynonym>
        <oboInOwl:hasRelatedSynonym>familial cerebral saccular aneurysm</oboInOwl:hasRelatedSynonym>
        <oboInOwl:id>MONDO:0016483</oboInOwl:id>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#ordo_disease"/>
        <rdfs:label>intracranial berry aneurysm</rdfs:label>
        <skos:exactMatch rdf:resource="http://identifiers.org/snomedct/703226008"/>
        <skos:exactMatch rdf:resource="http://linkedlifedata.com/resource/umls/id/CN230268"/>
        <skos:exactMatch rdf:resource="http://purl.obolibrary.org/obo/DOID_0060228"/>
        <skos:exactMatch rdf:resource="http://www.orpha.net/ORDO/Orphanet_231160"/>
        <skos:exactMatch rdf:resource="https://omim.org/phenotypicSeries/PS105800"/>
    </owl:Class>


    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0016483"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        <owl:annotatedTarget>OMIMPS:105800</owl:annotatedTarget>
        <oboInOwl:source>MONDO:cjm</oboInOwl:source>
        <oboInOwl:source>MONDO:equivalentTo</oboInOwl:source>
    </owl:Axiom>

    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0016483"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2004/02/skos/core#exactMatch"/>
        <owl:annotatedTarget rdf:resource="https://omim.org/phenotypicSeries/PS105800"/>
        <sssom:mapping_justification rdf:resource="https://w3id.org/semapv/UnspecifiedMatching"/>
        <sssom:subject_label>intracranial berry aneurysm</sssom:subject_label>
    </owl:Axiom>

```

There is no mentions of `DOID_0080964` in here. Is that expected?

**Comment by hrshdhgd** [comment]
Here's what the lexical index file shows:

```
omim:105800:
    term: omim:105800
    relationships:
    - predicate: oio:hasDbXref
      element: DOID:0080964
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasDbXref
      element: MONDO:0007111
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false
    - predicate: oio:hasDbXref
      element: Orphanet:231160
      element_term: OMIM:105800
      pipeline:
      - default
      synonymized: false

```

So if `hasDbXref` is uncommented in the `match_rules.yaml`, the `skos:exactMatch` will automatically appear.
