### ISSUE TITLE
GARD has been added to pipeline, why does it not show up in lexmatch?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#327]
There should be a GARD mapping file now in the lexmatch folder.

**Comment by joeflack4** [comment]
I'm unfamiliar with the lexmatch work. I thought about it but I should have asked about how to test this.

### 1. `mondo-sources-all-lexical.sssom.tsv`
One thing I'm seeing is for the `../mappings/mondo-sources-all-lexical.sssom.tsv` goal, one of the args is `-c metadata/mondo.sssom.config.yml`. This results from running `lexmatch-sssom-compare.py`. Here are some example entries in there:

```yml
  - from: MONDO
    to: ICD10CM
    metadata:
      object_source: https://www.icd10data.com/
      mapping_date: "2017-09-20"

  - from: MONDO
    to: Orphanet
    metadata:
      object_source: https://www.orpha.net/
      object_source_version: http://www.orphadata.org/data/ORDO/ordo_orphanet_3.1.owl
      mapping_date: "2021-07-06"
      comment: "The latest Orphanet is integrated with every Mondo release."
```

Do I need to add an entry for GARD there?

### 2. `lexmatch/`
I think if I do (1), (2) might follow. I don't see any goal for `lexmatch/unmapped_%_lex.tsv`, just `lexmatch/README.md`. But it looks like this results from running `match-mondo-sources-all-lexical.py`.

---

@matentzn If you want, perhaps @hrshdhgd and I can set up some time to pair program this. I can answer any questions he might have about GARD, I can learn about the lexmatch, and if you want, either at this time or in the future, we can standardize some of the lexmatch goals to be a bit more like the other goals (able to run for a single ontology at a time, etc).
